### ISSUE TITLE
Can it support youcompleteme?

### ISSUE THREAD

**Issue by tenfyzhong** [machakann/vim-Verdin#2] opened 2017-09-08 08:53 UTC

**Comment by machakann** [comment] 2017-09-08 11:39
As far as I know, youcompleteme uses 'omnifunc' option, thus `vim-Verdin` should work with it. As for the custom completer, no, it doesn't have.

**Comment by simlei** [comment] 2018-05-19 22:08
I conferred with the YCM people in their gitter because the omnifunc was not picked up correctly by YCM. The cutoff was 'YCM adheres to vim doc's standard regarding the omnifunc calling behavior, verdin does not." and that the omnifunc in Verdin was too complicated. 

One of the admonitions were:
```
Calling the omnifunc on an empty line in insert mode like it's supposed to:

echom Verdin#omnifunc(1, "")
echom string(Verdin#omnifunc(0, ''))
outputs 0 and [] so it's not a surprise that YCM returns nothing
```

Well, that may have been the one side of the view on this, but I'm here to confirm that the omnifunc of Verdin currently is not supported by YCM's omnifunc pickup mechanism. It would be nice to have it working, though!
The way to get it work would be definetely to make the omnifunc play nice with YCM, that is for sure. A custom completion engine tailored to YCM would not be necessary.

**Comment by machakann** [comment] 2018-05-20 01:36
I see. Indeed, `Verdin#omnifunc()` uses the `complete_add()` built-in function to display complete items. I don't want to change the implementation because it may break the current feeling of use.

However, for example, I can add a new option to avoid the use of such side-effective functions. If you set:

```vim
let g:Verdin#cooperativemode = 1
```

then, `Verdin#omnifunc()` returns a list of complete items. Could it be useful?

**Comment by machakann** [comment] 2018-05-20 10:05
You can test it on the `cooperativemode` branch.

**Comment by simlei** [comment] 2018-05-20 10:43
Super, I will try it out!

**Comment by simlei** [comment] 2018-05-21 14:02
okayy that seems to work exactly as expected: everything that C-x C-o would show is picke up by YCM's semantic completion mode.
![image](https://user-images.githubusercontent.com/982379/40311403-f479d6b4-5d0f-11e8-9e64-3dcf3c9003dd.png)
I did a test assignment to a variable named 'g:test' in the console. Verdin does not show that as can be seen, and neither the various global variables from the plugins I have, but that is beside the point of this issue. The issue was, to have it working with YCM, and it does now, at least with my machine, in the 'cooperativemode' branch. 

Thanks very much for introducing it! I will be keeping Verdin in my vimrc then and am hoping to make good use of it and possible future improvements :)

**Comment by machakann** [comment] 2018-05-21 14:30
Merged to master branch. Thank you for your help!

**Comment by bstaletic** [comment] 2018-05-21 14:32
With a low number of global variables in the buffer, my `g:v_test_var` did show int the buffer. This seems to really be working with YCM.

@machakann I'm one of the YCM developers and just wanted to say thanks for making Verdin play nice with YCM.

**Comment by machakann** [comment] 2018-05-21 14:44
@bstaletic Welcome!

@simlei Verdin gathers words only from the opened buffers and files in `g:Verdin#loadpath`. Thus, that is my expected behavior.

In the past, I have made it include the local variable names and function names, but I felt it was too noisy in plugin developments. I'm still wondering if the local variable name completion could be useful. When do you expect it useful? Maybe, I should think of it seriously.

**Comment by machakann** [comment] 2018-05-21 14:49
Ah, editing vimrc?

**Comment by simlei** [comment] 2018-05-21 16:24
@machakann yup, I have made some rube goldberg machine of vimrc so it does per-project and globally scoped config files for several plugins (like bookmarks...). Normally, the identifier extraction as YCM offers is quite enough though, when it picks up words from previously-opened files. I was just checking as to what the full extent of Verdin's Vimscript introspection may be.

Me personally, I would probably prefer to see variables I myself defined (in global context, to be sure) or that exist due to plugins. This is certainly protential feature creep and noysiness and should be handles wisely and probably only on opt in basis. You are right - it may just be useful for vimrc editing (as in, writing ad-hoc plugin stumps mostly. But another case would be, when adopting a new plugin: it could help with browsing through the global variables available as they commonly have a plugin-related prefix IF those variables are really present i.e. are assigned the default themselves when the user doesn't interfere. I bet not all plugin behave equally in really setting those global variables to the default if the user doesn't, though, and I can't tell from experience.

**Comment by simlei** [comment] 2018-11-03 14:46
I just wanted to tell that it continues to work unimpeded with YouCompleteMe, and this issue should be closed.
Also, your newest improvements were perceivable such that it brought me here ("that plugin hasn't been updated...? I can see more stuff in autocompletion now!")
Cheers, thanks!

**Comment by machakann** [comment] 2018-11-04 01:55
Thanks, I have thought I closed this already.

**Closed as completed by machakann** 2018-11-04 01:55 UTC
